### ISSUE TITLE
Project download missing

### ISSUE THREAD

**Issue by ashokvanam** [tonydemark/aws-lambda-wkhtmltoimage#1]
Hi,

Could you please provide the package to upload the function into AWS Lambda

This url is not downloading anything
https://github.com/tonydemark/aws-lambda-wkhtmltoimage/releases/download/0.1/wkhtmltoimage.zip

Regards
Ashok

**Comment by cosmok** [comment]
Link in Releases works:
https://github.com/tonydemark/aws-lambda-wkhtmltoimage/archive/0.1.zip

**Comment by ranjeetsinghr** [comment]
i downloaded zip and tried followed read me instruction. getting error as

{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'index'",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 'index'",
    "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:45:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
    "    at Module.load (internal/modules/cjs/loader.js:653:32)",
    "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
    "    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)",
    "    at startup (internal/bootstrap/node.js:283:19)"
  ]
}
